services:
  postgres:
    image: postgres:16-alpine
    container_name: detektif_data_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: detektif
      POSTGRES_PASSWORD: detektif123
      POSTGRES_DB: detektif_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
